#!/bin/bash -e

# If exporter.autostart is set to true in gadget snap, write the key permanently into snapd's local database

autostart="$(snapctl get exporter.autostart)"

if [ "$autostart" = "true" ]; then
    snapctl set exporter.autostart=true
fi